import { createHash, createHmac } from "node:crypto";
import { getConfig } from "@/lib/config";
import type { SaveFileInput, StorageProvider, StoredFile } from "@/lib/storage/provider";

type CloudinaryAsset = { public_id: string; version: number; format: string; bytes: number };
function parseKey(key: string) { const [publicId, version, format] = key.split("|"); if (!publicId || !version || !format) throw new Error("Invalid Cloudinary storage key"); return { publicId, version, format }; }
export class CloudinaryStorageProvider implements StorageProvider {
  private config = getConfig();
  private async save(input: SaveFileInput, prefix: string): Promise<StoredFile> { const timestamp = Math.floor(Date.now() / 1000); const publicId = `wv/${prefix}/${input.userId}/${crypto.randomUUID()}`; const signature = createHash("sha1").update(`public_id=${publicId}&timestamp=${timestamp}&type=authenticated${this.config.CLOUDINARY_API_SECRET}`).digest("hex"); const form = new FormData(); form.set("file", new Blob([new Uint8Array(input.data)], { type: input.mimeType }), input.filename); form.set("api_key", this.config.CLOUDINARY_API_KEY!); form.set("timestamp", String(timestamp)); form.set("type", "authenticated"); form.set("public_id", publicId); form.set("signature", signature); const response = await fetch(`https://api.cloudinary.com/v1_1/${this.config.CLOUDINARY_CLOUD_NAME}/${this.config.CLOUDINARY_ASSET_TYPE}/upload`, { method: "POST", body: form }); if (!response.ok) throw new Error(`Cloudinary upload failed (${response.status})`); const asset = await response.json() as CloudinaryAsset; return { provider: "cloudinary", storageKey: `${asset.public_id}|${asset.version}|${asset.format}`, byteSize: asset.bytes, mimeType: input.mimeType }; }
  saveOriginal(input: SaveFileInput) { return this.save(input, "originals"); }
  saveGenerated(input: SaveFileInput) { return this.save(input, "generated"); }
  private getCloudinaryDeliveryUrl(storageKey: string) { const { publicId, version, format } = parseKey(storageKey); const assetType = this.config.CLOUDINARY_ASSET_TYPE; const deliveryPath = `v${version}/${publicId}.${format}`; const signature = createHash("sha256").update(`${deliveryPath}${this.config.CLOUDINARY_API_SECRET}`).digest("base64url").slice(0, 8); return `https://res.cloudinary.com/${this.config.CLOUDINARY_CLOUD_NAME}/${assetType}/authenticated/s--${signature}--/${deliveryPath}`; }
  async getSecureUrl(storageKey: string, expiresInSeconds: number) { const expires = String(Math.floor(Date.now() / 1000) + expiresInSeconds); const signature = createHmac("sha256", this.config.STORAGE_SIGNING_SECRET).update(`${storageKey}:${expires}`).digest("hex"); return `/api/visualization/files?key=${encodeURIComponent(storageKey)}&expires=${expires}&signature=${signature}`; }
  async read(storageKey: string) { const response = await fetch(this.getCloudinaryDeliveryUrl(storageKey)); if (!response.ok) throw new Error("Cloudinary read failed"); return Buffer.from(await response.arrayBuffer()); }
  async delete(storageKey: string) { const { publicId } = parseKey(storageKey); const timestamp = Math.floor(Date.now() / 1000); const signature = createHash("sha1").update(`public_id=${publicId}&timestamp=${timestamp}${this.config.CLOUDINARY_API_SECRET}`).digest("hex"); const form = new URLSearchParams({ public_id: publicId, timestamp: String(timestamp), api_key: this.config.CLOUDINARY_API_KEY!, signature }); const response = await fetch(`https://api.cloudinary.com/v1_1/${this.config.CLOUDINARY_CLOUD_NAME}/image/destroy`, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: form }); if (!response.ok) throw new Error("Cloudinary delete failed"); }
}
