"use client";
import { useEffect, useState } from "react";

type Eligibility = { bmi: number; maximumSafeLossKg: number; recommendedCategory: string | null; categories: Array<{ code: string; nominalMinimumKg: number; effectiveMaximumKg: number; eligible: boolean; reason?: string }> };
type Identity = { userId: string; phone: string };

export default function VisualizationDev() {
  const [identity, setIdentity] = useState<Identity>({ userId: "", phone: "" }); const [file, setFile] = useState<File>(); const [height, setHeight] = useState(170); const [weight, setWeight] = useState(85); const [eligibility, setEligibility] = useState<Eligibility>(); const [category, setCategory] = useState("LOSS_3_5"); const [uploadId, setUploadId] = useState(""); const [job, setJob] = useState<{ id: string; status: string; resultUrl?: string }>(); const [message, setMessage] = useState(""); const [consent, setConsent] = useState(false); const [ownership, setOwnership] = useState(false);
  useEffect(() => setIdentity({ userId: localStorage.getItem("user_id") ?? "", phone: localStorage.getItem("phone") ?? "" }), []);
  const headers = () => ({ "x-user-id": identity.userId, "x-phone": identity.phone });
  async function checkEligibility() { const response = await fetch("/api/visualization/eligibility", { method: "POST", headers: { ...headers(), "content-type": "application/json" }, body: JSON.stringify({ user_id: identity.userId, phone: identity.phone, heightCm: height, weightKg: weight }) }); const json = await response.json(); if (response.ok) { setEligibility(json.data); setCategory(json.data.recommendedCategory ?? ""); } else setMessage(json.error?.message ?? "Eligibility failed"); }
  async function upload() { if (!file) return setMessage("Choose an image"); const form = new FormData(); form.set("file", file); form.set("user_id", identity.userId); form.set("phone", identity.phone); form.set("aiConsent", String(consent)); form.set("ownershipConfirmed", String(ownership)); const response = await fetch("/api/visualization/uploads", { method: "POST", headers: headers(), body: form }); const json = await response.json(); if (response.ok) setUploadId(json.data.id); else setMessage(json.error?.message ?? "Upload failed"); }
  async function generate() { const response = await fetch("/api/visualization/generations", { method: "POST", headers: { ...headers(), "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ uploadId, heightCm: height, weightKg: weight, categoryCode: category, user_id: identity.userId, phone: identity.phone }) }); const json = await response.json(); if (response.ok) setJob(json.data); else setMessage(json.error?.message ?? "Generation failed"); }
  useEffect(() => { if (!job?.id || job.status === "SUCCEEDED" || job.status === "FAILED") return; const timer = setInterval(async () => { const response = await fetch(`/api/visualization/generations/${job.id}`, { headers: headers() }); if (response.ok) setJob((await response.json()).data); }, 1500); return () => clearInterval(timer); }, [job?.id, job?.status, identity.userId, identity.phone]);
  return <main style={{ maxWidth: 720, margin: "2rem auto", fontFamily: "sans-serif" }}><h1>AI weight visualization tester</h1><p>This is an AI-generated visualization and not a medical prediction or guaranteed result.</p><p>Identity is read from localStorage keys <code>user_id</code> and <code>phone</code>, then verified against Supabase on every request.</p><label>User ID <input value={identity.userId} onChange={(event) => { setIdentity({ ...identity, userId: event.target.value }); localStorage.setItem("user_id", event.target.value); }} /></label><label> Phone <input value={identity.phone} onChange={(event) => { setIdentity({ ...identity, phone: event.target.value }); localStorage.setItem("phone", event.target.value); }} /></label><div><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0])} /></div><label><input type="checkbox" checked={ownership} onChange={(event) => setOwnership(event.target.checked)} /> I own this image or have permission to use it.</label><br /><label><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /> I consent to temporary AI processing.</label><div><label>Height cm <input type="number" value={height} onChange={(event) => setHeight(Number(event.target.value))} /></label><label> Weight kg <input type="number" value={weight} onChange={(event) => setWeight(Number(event.target.value))} /></label><button onClick={checkEligibility}>Check eligibility</button></div>{eligibility && <section><p>BMI: {eligibility.bmi}; maximum safe visualization loss: {eligibility.maximumSafeLossKg} kg</p>{eligibility.categories.map((item) => <label key={item.code} style={{ display: "block" }}><input type="radio" disabled={!item.eligible} checked={category === item.code} onChange={() => setCategory(item.code)} /> {item.code}: {item.nominalMinimumKg}–{item.effectiveMaximumKg} kg {item.reason ?? ""}</label>)}</section>}<button onClick={upload} disabled={!file || !consent || !ownership}>Upload original</button><button onClick={generate} disabled={!uploadId || !category}>Generate</button>{job && <p>Job status: {job.status} {job.resultUrl && <img src={job.resultUrl} alt="Generated visualization" style={{ maxWidth: 300, display: "block" }} />}</p>}{message && <p role="alert">{message}</p>}</main>;
}
